-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 21:04:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema attendanceapp_db_v0_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema attendanceapp_db_v0_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendanceapp_db_v0_2` DEFAULT CHARACTER SET utf8 ;
USE `attendanceapp_db_v0_2` ;

-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Department_column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Department_column` (
  `Department.id` INT UNSIGNED NOT NULL,
  `Department_Name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Department.id`),
  UNIQUE INDEX `Department_Name_UNIQUE` (`Department_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Year_column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Year_column` (
  `Year.id` INT UNSIGNED NOT NULL,
  `Year_Name` INT UNSIGNED NOT NULL,
  `Year_columncol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Year.id`, `Year_Name`),
  UNIQUE INDEX `Year_Name_UNIQUE` (`Year_Name` ASC) VISIBLE,
  UNIQUE INDEX `Year_columncol_UNIQUE` (`Year_columncol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Subject_column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Subject_column` (
  `Subject.id` INT UNSIGNED NOT NULL,
  `Subject_code` VARCHAR(6) NOT NULL,
  `Subject_name` VARCHAR(35) NOT NULL,
  `Subject_Clip` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Subject.id`),
  UNIQUE INDEX `Subject_code_UNIQUE` (`Subject_code` ASC) VISIBLE,
  UNIQUE INDEX `Subject_name_UNIQUE` (`Subject_name` ASC) VISIBLE,
  UNIQUE INDEX `Subject_Clip_UNIQUE` (`Subject_Clip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Class_Column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Class_Column` (
  `Class_id` INT UNSIGNED NOT NULL,
  `Class_Name` VARCHAR(6) NOT NULL,
  `Department_id_CC` INT UNSIGNED NULL,
  `Year_id_CC` INT UNSIGNED NULL,
  PRIMARY KEY (`Class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Day_Column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Day_Column` (
  `Day_id` INT UNSIGNED NOT NULL,
  `Day_Name` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Day_id`),
  UNIQUE INDEX `Day_id_UNIQUE` (`Day_id` ASC) VISIBLE,
  UNIQUE INDEX `Day_Name_UNIQUE` (`Day_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Student_Details_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Student_Details_Table` (
  `Student_id_DT` INT UNSIGNED NOT NULL,
  `Student_RegNO` VARCHAR(11) NOT NULL,
  `Student_Name` VARCHAR(45) NULL,
  `Class_Id_DT` INT UNSIGNED NULL,
  `Department_Id_DT` INT UNSIGNED NULL,
  `Year_Id_DT` INT UNSIGNED NULL,
  PRIMARY KEY (`Student_id_DT`),
  UNIQUE INDEX `Student_RegNO_DT_UNIQUE` (`Student_RegNO` ASC) VISIBLE,
  INDEX `CLass_id_DT_idx` (`Class_Id_DT` ASC) VISIBLE,
  INDEX `Department_id_DT_idx` (`Department_Id_DT` ASC) VISIBLE,
  INDEX `Year_id_DT_idx` (`Year_Id_DT` ASC) VISIBLE,
  CONSTRAINT `CLass_id_DT`
    FOREIGN KEY (`Class_Id_DT`)
    REFERENCES `attendanceapp_db_v0_2`.`Class_Column` (`Class_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Department_id_DT`
    FOREIGN KEY (`Department_Id_DT`)
    REFERENCES `attendanceapp_db_v0_2`.`Department_column` (`Department.id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Year_id_DT`
    FOREIGN KEY (`Year_Id_DT`)
    REFERENCES `attendanceapp_db_v0_2`.`Year_column` (`Year.id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Student_Login_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Student_Login_Table` (
  `Mail_id` VARCHAR(60) NOT NULL,
  `Password_Hash` VARCHAR(60) NULL,
  `Student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `Mail_id_UNIQUE` (`Mail_id` ASC) VISIBLE,
  UNIQUE INDEX `Student_id_UNIQUE` (`Student_id` ASC) VISIBLE,
  PRIMARY KEY (`Mail_id`),
  CONSTRAINT `Student_id_LT`
    FOREIGN KEY (`Student_id`)
    REFERENCES `attendanceapp_db_v0_2`.`Student_Details_Table` (`Student_id_DT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Student_Period_Attendance_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Student_Period_Attendance_table` (
  `Period_Attendance_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Student_id_PAT` INT UNSIGNED NULL,
  `Subject_id_PAT` INT UNSIGNED NULL,
  `Present_Class_Count` INT NULL,
  `Total_Class_Count` INT NULL,
  `Subject_Percentage` FLOAT GENERATED ALWAYS AS ((Present_Class_Count / Total_Class_Count) * 100) VIRTUAL,
  PRIMARY KEY (`Period_Attendance_id`),
  UNIQUE INDEX `idx_Id_SubId` (`Student_id_PAT` ASC, `Subject_id_PAT` ASC) VISIBLE,
  INDEX `Subject_id_PAT_idx` (`Subject_id_PAT` ASC) VISIBLE,
  CONSTRAINT `Subject_id_PAT`
    FOREIGN KEY (`Subject_id_PAT`)
    REFERENCES `attendanceapp_db_v0_2`.`Subject_column` (`Subject.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Student_id_PAT`
    FOREIGN KEY (`Student_id_PAT`)
    REFERENCES `attendanceapp_db_v0_2`.`Student_Details_Table` (`Student_id_DT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Schedule_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Schedule_table` (
  `Schedule_id` INT UNSIGNED NOT NULL,
  `Year_id_ST` INT UNSIGNED NOT NULL,
  `Class_id_ST` INT UNSIGNED NOT NULL,
  `Day_id_ST` INT UNSIGNED NOT NULL,
  `Period_No` INT UNSIGNED NOT NULL,
  `Subject_id_ST` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Schedule_id`),
  UNIQUE INDEX `idx_Schedule` (`Schedule_id` ASC, `Year_id_ST` ASC, `Class_id_ST` ASC, `Day_id_ST` ASC, `Period_No` ASC, `Subject_id_ST` ASC) VISIBLE,
  INDEX `Year_id_ST_idx` (`Year_id_ST` ASC) VISIBLE,
  INDEX `Class_id_ST_idx` (`Class_id_ST` ASC) VISIBLE,
  INDEX `Day_id_ST_idx` (`Day_id_ST` ASC) VISIBLE,
  INDEX `Subject_id_ST_idx` (`Subject_id_ST` ASC) VISIBLE,
  CONSTRAINT `Year_id_ST`
    FOREIGN KEY (`Year_id_ST`)
    REFERENCES `attendanceapp_db_v0_2`.`Year_column` (`Year.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Class_id_ST`
    FOREIGN KEY (`Class_id_ST`)
    REFERENCES `attendanceapp_db_v0_2`.`Class_Column` (`Class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Day_id_ST`
    FOREIGN KEY (`Day_id_ST`)
    REFERENCES `attendanceapp_db_v0_2`.`Day_Column` (`Day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Subject_id_ST`
    FOREIGN KEY (`Subject_id_ST`)
    REFERENCES `attendanceapp_db_v0_2`.`Subject_column` (`Subject.id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Student_Date_Attendane_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Student_Date_Attendane_Table` (
  `Attendance_id` INT UNSIGNED NOT NULL,
  `Student_id_DAT` INT UNSIGNED NOT NULL,
  `Semester_No` INT UNSIGNED NOT NULL,
  `Date` DATE NOT NULL,
  `Day_id_DAT` INT UNSIGNED NOT NULL,
  `Period1_Status` JSON NULL,
  `Period2_status` JSON NULL,
  `Period3_Status` JSON NULL,
  `Period4_Status` JSON NULL,
  `Period5_Status` JSON NULL,
  `Period6_Status` JSON NULL,
  `Period7_Status` JSON NULL,
  `Period8_Status` JSON NULL,
  PRIMARY KEY (`Attendance_id`),
  INDEX `Student_id_DAT_idx` (`Student_id_DAT` ASC) VISIBLE,
  UNIQUE INDEX `idx_ID_DATE_DAT` (`Attendance_id` ASC, `Date` ASC) VISIBLE,
  INDEX `Day_id_DAT_idx` (`Day_id_DAT` ASC) VISIBLE,
  CONSTRAINT `Student_id_DAT`
    FOREIGN KEY (`Student_id_DAT`)
    REFERENCES `attendanceapp_db_v0_2`.`Student_Details_Table` (`Student_id_DT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Day_id_DAT`
    FOREIGN KEY (`Day_id_DAT`)
    REFERENCES `attendanceapp_db_v0_2`.`Day_Column` (`Day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Staff_Details_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Staff_Details_Table` (
  `Staff_id_DT` INT UNSIGNED NOT NULL,
  `Staff_Name` VARCHAR(45) NULL,
  `Staff_RegNo` VARCHAR(11) NULL,
  PRIMARY KEY (`Staff_id_DT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendanceapp_db_v0_2`.`Staff_Login_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendanceapp_db_v0_2`.`Staff_Login_Table` (
  `Mail_id` VARCHAR(40) NOT NULL,
  `Password_Hash` VARCHAR(60) NOT NULL,
  `Staff_id` INT UNSIGNED NULL,
  UNIQUE INDEX `Mail_id_UNIQUE` (`Mail_id` ASC) VISIBLE,
  UNIQUE INDEX `Staff_id_UNIQUE` (`Staff_id` ASC) VISIBLE,
  PRIMARY KEY (`Mail_id`),
  CONSTRAINT `Staff_idLT`
    FOREIGN KEY (`Staff_id`)
    REFERENCES `attendanceapp_db_v0_2`.`Staff_Details_Table` (`Staff_id_DT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
